#include <bits/stdc++.h>
using namespace std;

/*
Given a string, we have to find out all subsequences of it. A String is a 
subsequence of a given String, that is generated by deleting some character of a given 
string without changing its order.
*/

void print_all_subsequences(string t, int index, int n, string s)
{
    if (index == n)
        cout << t << "\n";

    else
    {
        // without inclusing char at the current index
        print_all_subsequences(t, index + 1, n, s);
        // including the char at the current index
        t = t + s[index];
        // and calling the function with char included
        print_all_subsequences(t, index + 1, n, s);
    }
}

int main()
{
    string s = "abc";
    print_all_subsequences("", 0, s.length(), s);
    return 0;
}